### ISSUE TITLE
Blur.

### ISSUE THREAD

**Issue by lentsius-bark** [scaryrawr/gnome-focus#10]
The extension works like a charm. any chance of the extension also blurring the transparent background?

**Comment by scaryrawr** [comment]
It looks like this is supported by GNOME [Shell.BlurEffect](https://gjs-docs.gnome.org/shell01~0.1_api/shell.blureffect). Currently playing around to find sensible defaults and updating the settings pane.

![image](https://user-images.githubusercontent.com/661373/108939846-5d394f00-7620-11eb-9e3c-e45829efec7f.png)

**Comment by lentsius-bark** [comment]
That is insanely awesome. Looking forward to seeing how this looks eventually but I'll be sure to start making use of it immediately

**Comment by scaryrawr** [comment]
It looks like Blur Effect can cause gnome to crash, there's a [fix](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1673), but I'm not sure how soon the fix will actually be released.

**Comment by scaryrawr** [comment]
A version with blur is queued for publishing, there will be some issues for folks until the patches to gnome-shell roll out (so it's marked as "Experimental"). Will close this issue once it's been approved.

**Comment by scaryrawr** [comment]
The version with blur has been approved as [version 5](https://extensions.gnome.org/extension/3924/focus/)
