### ISSUE TITLE
Not working in GNOME 45.2

### ISSUE THREAD

**Issue by NFiorentini** [scaryrawr/gnome-focus#35]
`The settings of extension focus@scaryrawr.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
prefs<@file:///home/nick/.local/share/gnome-shell/extensions/focus@scaryrawr.github.io/prefs.js:4:30
@file:///home/nick/.local/share/gnome-shell/extensions/focus@scaryrawr.github.io/prefs.js:193:3
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
`

This was one of my favorite GNOME extensions and I'd love to have it again!

**Comment by scaryrawr** [comment]
I believe this should be fixed in #37 . Will update once the new version has been approved on gnome-extensions.

**Comment by scaryrawr** [comment]
Should be fixed with [latest release](https://extensions.gnome.org/extension/3924/focus/).

**Comment by NFiorentini** [comment]
Just got it from gnome-extensions.  Thank you so much, Scaryrawr!
