### ISSUE TITLE
not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by Philippe-AMIOT** [scaryrawr/gnome-focus#36]
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:0

Stack trace:
  prefs<@file:///home/user/.local/share/gnome-shell/extensions/focus@scaryrawr.github.io/prefs.js:4:30
  @file:///home/user/.local/share/gnome-shell/extensions/focus@scaryrawr.github.io/prefs.js:193:3
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by scaryrawr** [comment]
I believe this should be fixed with #37 . I've submitted an update to gnome-extensions for review.

**Comment by scaryrawr** [comment]
Should be fixed with [latest release](https://extensions.gnome.org/extension/3924/focus/).
