### ISSUE TITLE
Does not make current  window opaque.

### ISSUE THREAD

**Issue by Gustavekkj** [scaryrawr/gnome-focus#9]
Does not make current  window opaque when switching window.

**Comment by scaryrawr** [comment]
HI @Gustavekkj ! Are you clicking on the windows when you switch?

The opacity should only change when the focus has changed which is by default on `click`.

You can check your focus mode by running:
`gsettings get org.gnome.desktop.wm.preferences focus-mode`

I personally set mine to `mouse`

Other things to check/share are the extension settings for "Focus Opacity", "Inactive Opacity", and "Special Focus Opacity" in the extension's settings pane.

Thanks!

**Comment by holger-bauer** [comment]
I have the same issue. Does the etension work with wayland?

I have focus opacity at 100 and even tested focus-mode set to mouse.

**Comment by scaryrawr** [comment]
> I have the same issue. Does the extension work with wayland?
> 
> I have focus opacity at 100 and even tested focus-mode set to mouse.

It should work on Wayland.

I'm curious if I'm conflicting with other extensions, or if I made a bad assumption for some versions.

Are you able to share:
- OS: Fedora 33 (Workstation Edition) x86_64
- DE: GNOME 3.38.3
- WM: Mutter
- List of other extensions
- Is it all apps or a specific application?

**Comment by holger-bauer** [comment]
-     OS: Fedora 33 (Workstation Edition) x86_64 **silverblue**
-    DE: GNOME 3.38.3
-    WM: Mutter
-  I have no other extensions enabled.
- All apps behave this way. I noticed that when I open a dialog in an app, e.g. settings, that window is opaque.

**Comment by scaryrawr** [comment]
> * ```
>   OS: Fedora 33 (Workstation Edition) x86_64 **silverblue**
>   ```
> * DE: GNOME 3.38.3
> * WM: Mutter
> * I have no other extensions enabled.
> * All apps behave this way. I noticed that when I open a dialog in an app, e.g. settings, that window is opaque.

Thanks! I'll be able to spin up a VM and investigate.

**Comment by scaryrawr** [comment]
New version is being published to gnome extensions.

Thanks!

**Comment by scaryrawr** [comment]
The latest version (3) has been published to the store and I believe should fix this behavior

https://extensions.gnome.org/extension/3924/focus/

Thanks for filing!
